# Markdownlint Configuration
# This file configures markdownlint for the Kafka-RS project

# Enable most rules but disable some that don't work well with technical documentation
default: true

# Disable line length limits for technical documentation
MD013: false

# Allow inline HTML (needed for badges, mermaid diagrams, etc.)
MD033: false

# Allow duplicate headings (common in API documentation)
MD024: false

# Relax heading style requirements
MD003:
  style: "atx"

# Allow bare URLs (common in technical docs)
MD034: false

# Disable first line requirements (many docs start with badges)
MD041: false
